/**
 * Section 04B — Business & Social Growth (immersive ecosystem scene).
 * Boston corridors: OSM via BPDA neighborhoods. Cambridge corridors: OSM via curated corridor bboxes.
 * @global
 */
(function (global) {
  "use strict";

  var SATELLITES = [
    { key: "cafes", metric: "osm_cafe_count", label: "Cafes" },
    { key: "restaurants", metric: "osm_restaurant_count", label: "Restaurants" },
    { key: "bookstores", metric: "osm_bookstore_count", label: "Bookstores" },
    { key: "coworking", metric: "osm_coworking_count", label: "Coworking" },
  ];

  var TIER = {
    major: { radius: 14, glow: 28, labelSize: 12, pulse: 1 },
    medium: { radius: 10, glow: 20, labelSize: 10, pulse: 0.7 },
    minor: { radius: 7, glow: 14, labelSize: 9, pulse: 0.45 },
  };

  global.Section04BConfig = {
    viewBox: { width: 1400, height: 880 },
    viz: {
      businessCsvPath: "data/layer_b_business_density.csv",
      corridorCsvPath: "data/section_04b_corridor_osm.csv",
      activityCsvPath: "data/section_04b_ecosystem_activity.csv",
      housingCsvPath: "data/layer_a_housing_pressure.csv",
      innovationCsvPath: "data/layer_c_innovation_workforce.csv",
      ecosystemCsvPath: "data/greater_boston_academic_ecosystem.csv",
      ariaLabel:
        "Immersive map of Greater Boston academic corridors and the cafes, restaurants, bookstores, and coworking spaces that cluster around them",
    },
    regions: [
      { id: "cambridge", label: "Cambridge", layout: { cx: 0.2, cy: 0.28, rx: 0.16, ry: 0.2 } },
      { id: "fenway", label: "Fenway & Longwood", layout: { cx: 0.42, cy: 0.42, rx: 0.14, ry: 0.18 } },
      { id: "allston", label: "Allston & Brighton", layout: { cx: 0.3, cy: 0.58, rx: 0.12, ry: 0.14 } },
      { id: "downtown", label: "Downtown & Back Bay", layout: { cx: 0.67, cy: 0.36, rx: 0.2, ry: 0.25 } },
      { id: "harbor", label: "Harbor & South", layout: { cx: 0.55, cy: 0.78, rx: 0.2, ry: 0.12 } },
    ],
    hubs: [
      {
        id: "hub-harvard-square",
        tier: "major",
        cluster: "cambridge",
        name: "Harvard Square",
        subtitle: "Harvard Yard · Law · Kennedy · Longy",
        geoIds: [],
        institutionBbox: [42.363, -71.132, 42.392, -71.108],
        layout: { x: 0.14, y: 0.2 },
      },
      {
        id: "hub-kendall-mit",
        tier: "major",
        cluster: "cambridge",
        name: "Kendall / MIT",
        subtitle: "MIT · Kendall Square innovation",
        geoIds: [],
        institutionBbox: [42.355, -71.095, 42.365, -71.082],
        layout: { x: 0.26, y: 0.3 },
      },
      {
        id: "hub-cambridge-central",
        tier: "medium",
        cluster: "cambridge",
        name: "Cambridge Central",
        subtitle: "Central Square · MIT edge",
        geoIds: [],
        institutionBbox: [42.358, -71.112, 42.368, -71.098],
        layout: { x: 0.22, y: 0.38 },
      },
      {
        id: "hub-porter-square",
        tier: "medium",
        cluster: "cambridge",
        name: "Porter Square",
        subtitle: "Lesley · graduate housing corridor",
        geoIds: [],
        institutionBbox: [42.384, -71.122, 42.392, -71.112],
        layout: { x: 0.1, y: 0.34 },
      },
      {
        id: "hub-fenway-kenmore",
        tier: "major",
        cluster: "fenway",
        name: "Fenway–Kenmore",
        subtitle: "BU · Northeastern · Kenmore student strip",
        geoIds: ["bos_nbhd_34"],
        layout: { x: 0.44, y: 0.36 },
      },
      {
        id: "hub-longwood",
        tier: "major",
        cluster: "fenway",
        name: "Longwood Medical",
        subtitle: "Harvard Medical · MCPHS · Simmons",
        geoIds: ["bos_nbhd_28"],
        layout: { x: 0.48, y: 0.48 },
      },
      {
        id: "hub-mission-hill",
        tier: "medium",
        cluster: "fenway",
        name: "Mission Hill",
        subtitle: "Northeastern · Longwood access",
        geoIds: ["bos_nbhd_13"],
        layout: { x: 0.52, y: 0.54 },
      },
      {
        id: "hub-allston-bu",
        tier: "major",
        cluster: "allston",
        name: "Allston / BU West",
        subtitle: "Packard's Corner · Harvard Business edge",
        geoIds: ["bos_nbhd_24"],
        layout: { x: 0.28, y: 0.52 },
      },
      {
        id: "hub-brighton",
        tier: "medium",
        cluster: "allston",
        name: "Brighton",
        subtitle: "Boston College spillover · commuter housing",
        geoIds: ["bos_nbhd_25"],
        layout: { x: 0.34, y: 0.64 },
      },
      {
        id: "hub-back-bay",
        tier: "major",
        cluster: "downtown",
        name: "Back Bay",
        subtitle: "Berklee · NEC · Fisher · Emerson overflow",
        geoIds: ["bos_nbhd_02"],
        layout: { x: 0.56, y: 0.47 },
      },
      {
        id: "hub-downtown-crossing",
        tier: "major",
        cluster: "downtown",
        name: "Downtown Crossing",
        subtitle: "Suffolk · Emerson · Tufts Medical",
        geoIds: ["bos_nbhd_07"],
        layout: { x: 0.63, y: 0.34 },
      },
      {
        id: "hub-beacon-hill",
        tier: "medium",
        cluster: "downtown",
        name: "Beacon Hill",
        subtitle: "Suffolk campus quarter",
        geoIds: ["bos_nbhd_30"],
        layout: { x: 0.57, y: 0.2 },
      },
      {
        id: "hub-chinatown",
        tier: "medium",
        cluster: "downtown",
        name: "Chinatown",
        subtitle: "Tufts Medical · downtown student edge",
        geoIds: ["bos_nbhd_26"],
        layout: { x: 0.71, y: 0.46 },
      },
      {
        id: "hub-south-end",
        tier: "medium",
        cluster: "downtown",
        name: "South End",
        subtitle: "BU Medical Campus housing",
        geoIds: ["bos_nbhd_32"],
        layout: { x: 0.64, y: 0.58 },
      },
      {
        id: "hub-charlestown",
        tier: "minor",
        cluster: "downtown",
        name: "Charlestown",
        subtitle: "Bridge to Cambridge · waterfront commute",
        geoIds: ["bos_nbhd_04"],
        layout: { x: 0.5, y: 0.18 },
      },
      {
        id: "hub-seaport",
        tier: "medium",
        cluster: "downtown",
        name: "Seaport",
        subtitle: "Waterfront coworking · innovation offices",
        geoIds: ["bos_nbhd_29"],
        layout: { x: 0.82, y: 0.52 },
      },
      {
        id: "hub-bay-village",
        tier: "minor",
        cluster: "downtown",
        name: "Bay Village",
        subtitle: "Theater District edge",
        geoIds: ["bos_nbhd_33"],
        layout: { x: 0.69, y: 0.38 },
      },
      {
        id: "hub-west-end",
        tier: "minor",
        cluster: "downtown",
        name: "West End",
        subtitle: "Mass General · West End flats",
        geoIds: ["bos_nbhd_31"],
        layout: { x: 0.55, y: 0.28 },
      },
      {
        id: "hub-columbia-point",
        tier: "medium",
        cluster: "harbor",
        name: "Columbia Point",
        subtitle: "UMass Boston · harbor campus",
        geoIds: ["bos_nbhd_06"],
        layout: { x: 0.48, y: 0.78 },
      },
      {
        id: "hub-south-boston",
        tier: "minor",
        cluster: "harbor",
        name: "South Boston",
        subtitle: "Broadway · waterfront social strip",
        geoIds: ["bos_nbhd_17"],
        layout: { x: 0.68, y: 0.7 },
      },
      {
        id: "hub-jamaica-plain",
        tier: "minor",
        cluster: "harbor",
        name: "Jamaica Plain",
        subtitle: "Orange Line · neighborhood cafes",
        geoIds: ["bos_nbhd_11"],
        layout: { x: 0.36, y: 0.72 },
      },
      {
        id: "hub-north-end",
        tier: "minor",
        cluster: "downtown",
        name: "North End",
        subtitle: "Historic dining · tourist-social mix",
        geoIds: ["bos_nbhd_14"],
        layout: { x: 0.76, y: 0.18 },
      },
    ],
    hubLinks: [
      ["hub-harvard-square", "hub-kendall-mit"],
      ["hub-harvard-square", "hub-porter-square"],
      ["hub-harvard-square", "hub-cambridge-central"],
      ["hub-kendall-mit", "hub-cambridge-central"],
      ["hub-kendall-mit", "hub-charlestown"],
      ["hub-kendall-mit", "hub-fenway-kenmore"],
      ["hub-fenway-kenmore", "hub-longwood"],
      ["hub-fenway-kenmore", "hub-mission-hill"],
      ["hub-fenway-kenmore", "hub-allston-bu"],
      ["hub-fenway-kenmore", "hub-back-bay"],
      ["hub-longwood", "hub-mission-hill"],
      ["hub-allston-bu", "hub-brighton"],
      ["hub-allston-bu", "hub-back-bay"],
      ["hub-back-bay", "hub-downtown-crossing"],
      ["hub-back-bay", "hub-bay-village"],
      ["hub-downtown-crossing", "hub-beacon-hill"],
      ["hub-downtown-crossing", "hub-chinatown"],
      ["hub-downtown-crossing", "hub-west-end"],
      ["hub-downtown-crossing", "hub-seaport"],
      ["hub-chinatown", "hub-south-end"],
      ["hub-south-end", "hub-longwood"],
      ["hub-charlestown", "hub-north-end"],
      ["hub-columbia-point", "hub-jamaica-plain"],
      ["hub-columbia-point", "hub-south-boston"],
      ["hub-seaport", "hub-south-boston"],
    ],
    satellites: SATELLITES,
    tiers: TIER,
    colors: {
      hub: { major: "#e8c872", medium: "#c9a962", minor: "#8b7355" },
      hubStroke: "#fffbeb",
      link: "rgba(232, 200, 114, 0.12)",
      linkActive: "rgba(232, 200, 114, 0.42)",
      region: "rgba(232, 200, 114, 0.04)",
      regionLabel: "rgba(254, 243, 199, 0.22)",
      satellite: {
        cafes: "#d4a574",
        restaurants: "#c67b4e",
        bookstores: "#9a8fb8",
        coworking: "#7a9eae",
      },
      core: "rgba(255, 251, 235, 0.95)",
    },
  };
})(typeof window !== "undefined" ? window : this);
